### PR TITLE
Choice Cells and Menu Cells do not take which properties are available into account for uniqueness

### LINKED ISSUE #445: Choice Cells and Menu Cells do not take which properties are available into account for uniqueness
### Bug Report
References the iOS bug report: https://github.com/smartdevicelink/sdl_ios/issues/1940

When determining uniqueness, we should take into account what will be displayed to the user, not just all available properties. For example, if a head unit does not support menu cell secondary text but that is the only uniquing factor between two cells, both will still be displayed on a 7.1+ head unit despite them appearing exactly the same.

##### Reproduction Steps
1. Connect to a 7.1+ module that does not support secondary text
2. Create two menu cells that are identical except for secondary text
3. Display the two menu cells

##### Expected Behavior
The cells cannot be displayed because they are identical, or the cells have a uniquing factor applied to the primary text

##### Observed Behavior
The cells are displayed on the head unit identically

##### Browser & Version Information
* SDL JavaScript Suite Module: Both modules
* SDL JavaScript Version: 1.3.0
* Testing Against: Manticore with core 7.1.0

### PR DESCRIPTION
**Pull request by renonick87**
Fixes #445 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have verified that this PR passes lint validation
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

### Summary
This PR updates the screen manager (menu manager and choice manager) to check the uniqueness of cells based on available screen properties on RPC v7.1+

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js [hunk 1]
```diff
@@ -594,20 +621,81 @@ class _ChoiceSetManagerBase extends _SubManagerBase {
             .setKeypressMode(KeypressMode.RESEND_CURRENT_ENTRY);
     }
 
+    /**
+     * Clones a list of choice cells
+     * @param {ChoiceCell[]} originalList - A list of choice cells to be cloned
+     * @returns {ChoiceCell[]} - The cloned
```
Comment (crokita) [inline lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js:627]:
```suggestion
     * @returns {ChoiceCell[]|null} - The cloned choice cell list
```

File: lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js [hunk 2]
```diff
@@ -594,20 +621,81 @@ class _ChoiceSetManagerBase extends _SubManagerBase {
...
                 || (this._lifecycleManager.getSdlMsgVersion().getMajorVersion() === 7 && this._lifecycleManager.getSdlMsgVersion().getMinorVersion() === 0))) {
             // version if 7.0.0 or lower
-            this._addUniqueNamesToCells(choices);
+            this._addUniqueNamesToCells(choicesClone);
+        } else {
+            const strippedCellsClone = this._removeUnusedProperties(choicesClone);
+            this._addUniqueNamesBasedOnStrippedCells(strippedCellsClone, choicesClone);
+        }
+        this._preloadedChoices.forEach((preloadedChoice) => {
+            _ArrayTools.arrayRemove(choicesClone, preloadedChoice);
```
Comment (crokita) [inline lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js:654]: _ArrayTools.arrayRemove's method does not mutate the first argument, so choicesClone will not be changed by the end. Clever use of `reduce` can resolve this:

`return this._preloadedChoices.reduce((filteredChoices, choice) => _ArrayTools.arrayRemove(filteredChoices, choice), choicesClone);`

File: lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js [hunk 3]
```diff
@@ -594,20 +621,81 @@ class _ChoiceSetManagerBase extends _SubManagerBase {
...
+        });
+        return choicesClone; // deep copy
+    }
+
+    _removeUnusedProperties (choiceCells) {
```
Comment (crokita) [inline lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js:659]: Missing JSDocs

**Review by crokita — CHANGES_REQUESTED** [review]
See feedback

File: lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js [hunk 4]
```diff
@@ -594,20 +623,85 @@ class _ChoiceSetManagerBase extends _SubManagerBase {
...
             // version if 7.0.0 or lower
-            this._addUniqueNamesToCells(choices);
+            this._addUniqueNamesToCells(choicesClone);
+        } else {
+            const strippedCellsClone = this._removeUnusedProperties(choicesClone);
+            this._addUniqueNamesBasedOnStrippedCells(strippedCellsClone, choicesClone);
         }
-        return choices.map(choice => choice.clone()); // deep copy
+        return this._preloadedChoices.reduce((filteredChoices, currentChoice) => {
+            return _ArrayTools.arrayRemove(filteredChoices, currentChoice);
```
Comment (crokita) [inline lib/js/src/manager/screen/choiceset/_ChoiceSetManagerBase.js:656]: Just realized that a clone of choices is being passed into here, and arrayRemove does equality by reference comparison, which means that no matching choices would ever get removed. arrayRemove would have to be replaced by some other filter method that utilizes the equality check for choices instead.

**Review by crokita — CHANGES_REQUESTED** [review]
See feedback

**Review by crokita — APPROVED** [review]
