### PR TITLE
Fix for voice command that contains no string should be removed

### LINKED ISSUE #431: voiceCommand that contains no string should be removed
### Bug Report
When a voice command contains no strings, it should not be sent in an update

##### Reproduction Steps
1. voiceCommandA = ["Test 1"];
2. voiceCommandB = [];
3. Upload voiceCommands

##### Expected Behavior
currentVoiceCommands = [voiceCommandA];

##### Observed Behavior
currentVoiceCommands = [voiceCommandA, voiceCommandB];

### PR DESCRIPTION
**Pull request by renonick87**
Fixes #431 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have verified that this PR passes lint validation
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

##### Bug Fixes
* Removes empty voice commands from the list of voice commands to be set by the operation and does not perform an operation if there are no voice commands left.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: lib/js/src/manager/screen/_VoiceCommandManagerBase.js [hunk 1]
```diff
@@ -142,6 +150,27 @@ class _VoiceCommandManagerBase extends _SubManagerBase {
         });
     }
 
+    /**
+     * Remove all voice command strings consisting of just whitespace characters as the module will reject any "empty" strings.
+     * @param {VoiceCommands[]} voiceCommands - An array of VoiceCommands.
+     * @returns {VoiceCommands[]} - An array of VoiceCommands with empty VoiceCommands removed.
+     */
+    _removeEmptyVoiceCommands (voiceCommands) {
```
Comment (crokita) [inline lib/js/src/manager/screen/_VoiceCommandManagerBase.js:158]: This is very good

**Review by crokita — APPROVED** [review]

**Review by crokita — APPROVED** [review]
