### PR TITLE
Feature/rc1 fixes

### LINKED ISSUE #123: [SDL 0272] JavaScript Suite SDL Manager
Proposal: [JavaScript Suite SDL Manager](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0272-sdl-javascript-manager-layer.md)

> In a similar vein to [this proposal](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0171-android-manager-apis.md), the goal is to introduce a manager layer to the JavaScript Suite, closely matching the Java Suite and iOS manager APIs. These manager classes are designed to abstract out complex flows and states for common tasks, such as file handling and displaying information to the screen. 

Review: https://github.com/smartdevicelink/sdl_evolution/issues/901

Steering Committee Decision:

> The Steering Committee voted to accept this proposal with the revisions listed below:

- (Item 2) Pass an AppConfig instance into the SDLManager constructor.  The SDLManager `start()` method can perform the basic validation checks prior to starting the LifecycleManager to ensure the minimum properties of an AppConfig are provided, as well as a ManagerListener being defined.
- (Item 3) Single-method listeners to be replaced with simple JavaScript-oriented callback functions.
- (Item 7) Promises should be returned by manager methods which ultimately send one or more RPCs resulting in a single response. Developers then have the freedom to decide if/how they would like to handle the resolution or rejection of the RPC response. 
- (Item 12) Remove `getInternalInterface()` in favor of utilizing the reference to the LifecycleManager

> The proposal .md file was updated to reflect these revisions on 3/3/2020.

### PR DESCRIPTION
**Pull request by crokita**
Partially resolves #123 

This PR is **ready** for review.

### Summary
Bug fixes and improvements needed before the release of the JavaScript suite.

### CODE REVIEW

File: tests/Validator.js [hunk 1]
```diff
@@ -473,10 +473,10 @@ class Validator {
     /**
      * Test a basic RpcRequest or RpcResponse with no params set.
      * @param {String} functionName
-     * @param {RpcType} messageType
+     * @param {RpcType} MessageType
```
Comment (crokita) [inline tests/Validator.js]:
```suggestion
     * @param {RpcType} messageType
```

File: tests/Validator.js [hunk 2]
```diff
@@ -473,10 +473,10 @@ class Validator {
...
      * @param {RpcRequest|RpcResponse} msg
      */
-    static testNullBase (functionName, messageType, msg) {
+    static testNullBase (functionName, MessageType, msg) {
```
Comment (crokita) [inline tests/Validator.js]:
```suggestion
    static testNullBase (functionName, messageType, msg) {
```

File: tests/Validator.js [hunk 3]
```diff
@@ -487,7 +487,7 @@ class Validator {
             Validator.assertNullOrUndefined(correlationId, 'Correlation ID of the RPC message was not null.');
         }
         Validator.assertNotNull(msg.getRPCType(), 'Message type of the RPC message was null.');
-        Validator.assertEquals(messageType, msg.getRPCType(), 'Message type didn\'t match expected message type.');
+        Validator.assertEquals(MessageType, msg.getRPCType(), 'Message type didn\'t match expected message type.');
```
Comment (crokita) [inline tests/Validator.js]:
```suggestion
        Validator.assertEquals(messageType, msg.getRPCType(), 'Message type didn\'t match expected message type.');
```

File: tests/node/rpc/messages/BaseRpcTests.js [hunk 4]
```diff
@@ -39,9 +39,9 @@ exports.tests = function () {
     });
 
     it('testRPCType', function (done) {
-        const messageType = this.msg.getRPCType();
-        Validator.assertNotNullUndefined(messageType);
-        Validator.assertEquals(messageType, this.getRPCType());
+        const MessageType = this.msg.getRPCType();
```
Comment (crokita) [inline tests/node/rpc/messages/BaseRpcTests.js]:
```suggestion
        const messageType = this.msg.getRPCType();
```

File: tests/node/rpc/messages/BaseRpcTests.js [hunk 5]
```diff
@@ -39,9 +39,9 @@ exports.tests = function () {
...
+        Validator.assertNotNullUndefined(MessageType);
```
Comment (crokita) [inline tests/node/rpc/messages/BaseRpcTests.js]:
```suggestion
        Validator.assertNotNullUndefined(messageType);
```

File: tests/node/rpc/messages/BaseRpcTests.js [hunk 6]
```diff
@@ -39,9 +39,9 @@ exports.tests = function () {
...
+        Validator.assertEquals(MessageType, this.getRPCType());
```
Comment (crokita) [inline tests/node/rpc/messages/BaseRpcTests.js]:
```suggestion
        Validator.assertEquals(messageType, this.getRPCType());
```

File: examples/js/hello-sdl/index.html [hunk 7]
```diff
@@ -59,59 +59,103 @@
...
-                const putFile = await fileManager.createPutFile(file);
-                const setAppIcon = new SDL.rpc.messages.SetAppIcon()
-                    .setFileName(fileName);
-
-                await this._sdlManager.sendSequentialRpcs([
-                    putFile,
-                    setAppIcon,
+                screenManager.setVoiceCommands([
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 1'], () => {
+                        console.log('Option one has been clicked!');
```
Comment (crokita) [inline examples/js/hello-sdl/index.html]:
```suggestion
                        console.log('Option one selected!');
```

File: examples/js/hello-sdl/index.html [hunk 8]
```diff
@@ -59,59 +59,103 @@
...
+                    }),
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 2'], () => {
+                        console.log('Option two has been clicked!');
```
Comment (crokita) [inline examples/js/hello-sdl/index.html]:
```suggestion
                        console.log('Option two selected!');
```

File: examples/js/hello-sdl/index.html [hunk 9]
```diff
@@ -59,59 +59,103 @@
...
+                    }),
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 3'], () => {
+                        console.log('Option three has been clicked!');
```
Comment (crokita) [inline examples/js/hello-sdl/index.html]:
```suggestion
                        console.log('Option three selected!');
```

File: examples/js/hello-sdl/index.html [hunk 10]
```diff
@@ -59,59 +59,103 @@
...
 
                 // wait for the FULL state for more functionality
                 if (hmiLevel === SDL.rpc.enums.HMILevel.HMI_FULL) {
-                    const show = new SDL.rpc.messages.Show();
-                    show.setMainField1('Hello')
-                        .setMainField2('こんにちは')
-                        .setMainField3('你好');
-
-                    await this._sdlManager.sendRpc(show);
+                    const art1 = new SDL.manager.file.filetypes.SdlArtwork('fef2', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```
Comment (crokita) [inline examples/js/hello-sdl/index.html]:
```suggestion
                    const art1 = new SDL.manager.file.filetypes.SdlArtwork('logo', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```

File: examples/node/hello-sdl/AppClient.js [hunk 11]
```diff
@@ -99,26 +99,28 @@ class AppClient {
...
-            .setFileName(fileName);
-
-        await this._sdlManager.sendSequentialRpcs([
-            putFile,
-            setAppIcon,
+        // add voice commands for when the managers are ready
+        const screenManager = this._sdlManager.getScreenManager();
+        screenManager.setVoiceCommands([
+            new SDL.manager.screen.utils.VoiceCommand(['Option 1'], () => {
+                console.log('Option one has been clicked!');
```
Comment (crokita) [inline examples/node/hello-sdl/AppClient.js]:
```suggestion
                console.log('Option one selected!');
```

File: examples/node/hello-sdl/AppClient.js [hunk 12]
```diff
@@ -99,26 +99,28 @@ class AppClient {
...
+            }),
+            new SDL.manager.screen.utils.VoiceCommand(['Option 2'], () => {
+                console.log('Option two has been clicked!');
```
Comment (crokita) [inline examples/node/hello-sdl/AppClient.js]:
```suggestion
                console.log('Option two selected!');
```

File: examples/node/hello-sdl/AppClient.js [hunk 13]
```diff
@@ -99,26 +99,28 @@ class AppClient {
...
+            }),
+            new SDL.manager.screen.utils.VoiceCommand(['Option 3'], () => {
+                console.log('Option three has been clicked!');
```
Comment (crokita) [inline examples/node/hello-sdl/AppClient.js]:
```suggestion
                console.log('Option three selected!');
```

File: examples/node/hello-sdl/AppClient.js [hunk 14]
```diff
@@ -127,13 +129,35 @@ class AppClient {
 
         // wait for the FULL state for more functionality
         if (hmiLevel === SDL.rpc.enums.HMILevel.HMI_FULL) {
-            const show = new SDL.rpc.messages.Show();
-            show.setMainField1('Hello')
-                .setMainField2('こんにちは')
-                .setMainField3('你好');
+            const art1 = new SDL.manager.file.filetypes.SdlArtwork('fef2', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```
Comment (crokita) [inline examples/node/hello-sdl/AppClient.js]:
```suggestion
            const art1 = new SDL.manager.file.filetypes.SdlArtwork('logo', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```

File: examples/webengine/hello-sdl/index.html [hunk 15]
```diff
@@ -33,103 +33,143 @@
...
-                    const setAppIcon = new SDL.rpc.messages.SetAppIcon()
-                        .setFileName(fileName);
-
-                    await this._asyncSendRpc(setAppIcon);
-                }
+                // add voice commands for when the managers are ready
+                const screenManager = this._sdlManager.getScreenManager();
+                screenManager.setVoiceCommands([
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 1'], () => {
+                        console.log('Option one has been clicked!');
```
Comment (crokita) [inline examples/webengine/hello-sdl/index.html]:
```suggestion
                        console.log('Option one selected!');
```

File: examples/webengine/hello-sdl/index.html [hunk 16]
```diff
@@ -33,103 +33,143 @@
...
+                    }),
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 2'], () => {
+                        console.log('Option two has been clicked!');
```
Comment (crokita) [inline examples/webengine/hello-sdl/index.html]:
```suggestion
                        console.log('Option two selected!');
```

File: examples/webengine/hello-sdl/index.html [hunk 17]
```diff
@@ -33,103 +33,143 @@
...
+                    }),
+                    new SDL.manager.screen.utils.VoiceCommand(['Option 3'], () => {
+                        console.log('Option three has been clicked!');
```
Comment (crokita) [inline examples/webengine/hello-sdl/index.html]:
```suggestion
                        console.log('Option three selected!');
```

File: examples/webengine/hello-sdl/index.html [hunk 18]
```diff
@@ -33,103 +33,143 @@
...
                 // wait for the FULL state for more functionality
                 if (hmiLevel === SDL.rpc.enums.HMILevel.HMI_FULL) {
-                    const show = new SDL.rpc.messages.Show();
-                    show.setMainField1('Hello')
-                        .setMainField2('こんにちは')
-                        .setMainField3('你好')
-                        .setMainField4('Привіт');
-
-                    await this._asyncSendRpc(show);
+                    const art1 = new SDL.manager.file.filetypes.SdlArtwork('fef2', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```
Comment (crokita) [inline examples/webengine/hello-sdl/index.html]:
```suggestion
                    const art1 = new SDL.manager.file.filetypes.SdlArtwork('logo', SDL.rpc.enums.FileType.GRAPHIC_PNG)
```
