### PR TITLE
Apply fix to alert icon not uploading

### LINKED ISSUE #558: Images not displaying correctly on Alerts sent via AlertManager
### Bug Summary

This issue is related to the [Java Suite issue](https://github.com/smartdevicelink/sdl_java_suite/issues/1835)

When passing in a custom image to the icon property of an AlertView, the image is not displayed on the HMI.

### Reproduction Steps

1. Create an AlertView
2. Call setIcon and pass in an SdlArtwork with a custom image
3. Send it via screen manager's presentAlert

Expected Behavior:
The uploaded image displays in the alert on the Generic HMI

Observed Behavior:
A default image is displayed on the Generic HMI

### Which projects have you seen this bug on?

_No response_

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by crokita**
Fixes #558 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Tests the Alert RPC generation when an AlertView has an icon

### Summary
_PresentAlertOperation now keeps track of uploaded artwork names and uses it to check whether to attach the AlertView icon to the Alert RPC.

### CODE REVIEW

**Comment by crokita** [comment]
Note: artworksToBeUploaded line addition needs to filter out failed image uploads first before being used

File: lib/js/src/manager/screen/utils/_PresentAlertOperation.js [hunk 1]
```diff
@@ -227,6 +232,19 @@ class _PresentAlertOperation extends _Task {
...
+
+            const artworkResults = [];
+            for (let index = 0; index < successes.length; index++) {
+                artworkResults.push({
+                    artwork: artworksToBeUploaded[index],
+                    success: successes[index],
+                });
+            }
+            // only keep artworks that have been uploaded successfully by the file manager
+            const artworkNamesSuccessfullyUploaded = artworkResults.filter(result => result.success).map(result => result.artwork.getName());
```
Comment (renonick87) [inline lib/js/src/manager/screen/utils/_PresentAlertOperation.js:244]: It seems odd to me here that we have a loop to build `artworkResults` into an array of JSON objects only for it to be filtered and torn down immediately after. 
We should be able to condense this to one loop that simply checks the success result, then only pushes the artwork name to the array when `success=true`.
```suggestion
            const artworkNamesSuccessfullyUploaded = [];
            for (let index = 0; index < successes.length; index++) {
            // only keep artworks that have been uploaded successfully by the file manager
                if (successes[index]) {
                    artworkNamesSuccessfullyUploaded.push(artworksToBeUploaded[index].getName());
                }
            }
```

**Review by renonick87 — CHANGES_REQUESTED** [review]

**Review by renonick87 — APPROVED** [review]
