### PR TITLE
PermissionManager should convert old permissions to RPCStructs after cloning them

### LINKED ISSUE #422: PermissionManager crashes after receiving OnPermissionsChange
### Bug Report
When the JavaScript Suite receives an OnPermissionsChange notification from core, the PermissionManager will clone the old unchanged permissions but does not convert them to the correct PermissionItem class. The manager may later try to call `getHmiPermissions` on these old permission items but this fails because the old items are Objects and not instances of the PermissionItem class.

##### Reproduction Steps
1. Connect a JavaScript Suite app to core.
2. Trigger a PTU that updates the permissions for an RPC for which the app has access.
3. Call `PermissionManager.isRpcAllowed` for the RPC to check the updated permissions.

##### Expected Behavior
The manager should return a boolean value denoting whether the RPC is allowed or not.

##### Observed Behavior
The manager crashes because it is trying to call an RPCStruct method on a plain JavaScript Object.

##### Browser & Version Information
* SDL JavaScript Suite Module: node.
* SDL JavaScript Version: The most recent commit to the release/1.3.0_RC branch.
* Testing Against: The most recent commit to the sdl_core release/7.1.0-RC branch.

### PR DESCRIPTION
**Pull request by renonick87**
Fixes #422 

### Risk
This PR makes **no** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have verified that this PR passes lint validation
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

##### Bug Fixes
This PR fixes the case where an app would receive an OnPermissionsChange notification from core and clone its old PermissionItems but not convert them to PermissionItems.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

File: lib/js/src/manager/permission/_PermissionManagerBase.js [hunk 1]
```diff
@@ -64,7 +65,11 @@ class _PermissionManagerBase extends _SubManagerBase {
 
         this._onPermissionsChangeListener = (notification) => {
             const permissionItems = notification.getPermissionItem();
-            const previousPermissionItems = JSON.parse(JSON.stringify(this._currentPermissionItems));
+            const previousPermissionItemsJson = JSON.parse(JSON.stringify(this._currentPermissionItems));
+            const previousPermissionItems = {};
+            Object.entries(previousPermissionItemsJson).map((functionId, permissionObject) => {
```
Comment (crokita) [inline lib/js/src/manager/permission/_PermissionManagerBase.js:70]: Object.entries returns an array of arrays. When mapping over this, the `functionId` parameter holds the two desired values and `permissionObject` is holding the index. Instead, the signature should be: 
```
.map(([functionId, permissionObject]) => {
})

OR

.map(pair => {
   const functionId = pair[0]
   const permissionObject = pair[1]
})
```
See here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/entries#examples

**Review by crokita — COMMENTED** [review]
See feedback

**Review by crokita — APPROVED** [review]
