### PR TITLE
Bugfix/softbutton image upload

### LINKED ISSUE #541: ScreenManager tries to upload images even if they are not supported (SDL 2.0)
### Bug Summary

Bug report is from https://github.com/smartdevicelink/sdl_java_suite/issues/1738

### Bug Report
It seems the `ScreenManager` tries to upload images on Sync 2 even if the dynamic images are not supported. That doesn't crash the app but it just sends RPCs when there is no need for that. It also logs some error messages like the following:

```
E/FileManager: 5.2.0: File named icon.png failed to upload. Max number of upload attempts reached.
E/FileManager: 5.2.0: File named image1.png failed to upload. Max number of upload attempts reached.
E/SoftButtonReplaceOperation: 5.2.0: Error uploading soft button artworks: [image1.png]
E/FileManager: 5.2.0: File named image2.png failed to upload. Max number of upload attempts reached.
E/SoftButtonReplaceOperation: 5.2.0: Error uploading soft button artworks: [image2.png]
```

The potential reason for the issue is that Sync 2 sends `RegisterAppInterfaceResponse` with the following values:

```
RegisterAppInterfaceResponse.displayCapabilities.graphicSupported = false
RegisterAppInterfaceResponse.softButtonCapabilities.imageSupported = true
```
The `SoftButtonManager` (and possibly other managers) depends on `ImageSupported` and thinks the images are supported when in reality they are not.

### Reproduction Steps

The JavaScript will not be able to run on Sync 2. Instead it should match the code changes made from the other mobile libraries.

### Which projects have you seen this bug on?

_No response_

### JavaScript Version(s)

1.5.0

### sdl_javascript Version

1.5.0

### Testing Environment(s)

```markdown
N/A
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by crokita**
Fixes #541 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

Bug appears on Sync 2 which we cannot test with the JavaScript Suite library. Therefore we will check with unit tests and match the changes made on the other libraries.

### Summary
[See related PR](https://github.com/smartdevicelink/sdl_java_suite/pull/1811)

### CODE REVIEW

File: lib/js/src/manager/screen/_SoftButtonManagerBase.js [hunk 1]
```diff
@@ -60,6 +60,12 @@ class _SoftButtonManagerBase extends _SubManagerBase {
         this._currentMainField1 = null;
         this._currentHmiLevel = null;
         this._batchUpdates = false; // whether to wait on sending the updates
+        this._displayCapabilities = null;
+        if (lifecycleManager.getSystemCapabilityManager() !== null) {
+            this._displayCapabilities = lifecycleManager.getSystemCapabilityManager().getDisplayCapabilities();
+        }
+        this._isDynamicGraphicSupported = (this._displayCapabilities !== null && this._displayCapabilities.getGraphicSupported() !== null) ? this._displayCapabilities.getGraphicSupported() : true;
```
Comment (renonick87) [inline lib/js/src/manager/screen/_SoftButtonManagerBase.js:67]:
```suggestion
        let displayCapabilities = null;
        if (lifecycleManager.getSystemCapabilityManager() !== null) {
            displayCapabilities = lifecycleManager.getSystemCapabilityManager().getDisplayCapabilities();
        }
        this._isDynamicGraphicSupported = (displayCapabilities !== null && displayCapabilities.getGraphicSupported() !== null) ? displayCapabilities.getGraphicSupported() : true;
```
We don't use the display capabilities elsewhere in the operation so we don't need to save it. This also aligns better with the Java implementation.

**Review by renonick87 — APPROVED** [review]
