### PR TITLE
Make managers aware of artwork overwrite property

### LINKED ISSUE #365: Setting a `SDLArtwork`'s `overwrite` property to true does not work with screen manager
### Bug Report
Report based on this one: https://github.com/smartdevicelink/sdl_ios/issues/1117

If you try to set another artwork using the screen manager with a different file but under the same name with overwrite set to true, the new artwork will not show.

##### Reproduction Steps
1. Connect app to Core
1. Send a show request with the `graphic` set to an artwork named "TestArtwork"
1. Send a second show request with the `graphic` set  to a different artwork also named "TestArtwork". Set the artwork's `overwrite` property to `true` and `persistent` property to `false`.

##### Expected Behavior
The new artwork will show up in the `graphic` field of the template.

##### Observed Behavior
The `graphic` field of the template shows the old artwork.

##### Version Information
* SDL JavaScript Suite Module: NodeJS and vanilla JS libraries
* SDL JavaScript Version: Version 1.2
* Testing Against: Using a Node TCP app

### PR DESCRIPTION
**Pull request by crokita**
Fixes #365 

### Risk
This PR makes no API changes.

### Summary
Updates the SdlFile class to include the overwrite property, and updates the SoftButtonManager and the TextAndGraphicManager to recognize the use of the overwrite value.

### CODE REVIEW

File: lib/js/src/manager/file/_FileManagerBase.js [hunk 1]
```diff
@@ -230,6 +230,25 @@ class _FileManagerBase extends _SubManagerBase {
...
+
+    /**
+     * Check if an SdlFile needs to be uploaded to Core or not.
+     * It is different from hasUploadedFile() because it takes isStaticIcon and overwrite properties into consideration.
+     * ie, if the file is static icon, the method always returns false.
+     * If the file is dynamic, it returns true in one of these situations:
+     * 1) the file has the overwrite property set to true
+     * 2) the file hasn't been uploaded to Core before.
+     *
+     * @param {SdlFile} sdlFile - SdlFile with file name and one of A) fileData, B) Uri, or C) resourceID set
```
Comment (renonick87) [inline lib/js/src/manager/file/_FileManagerBase.js:243]:
```suggestion
     * @param {SdlFile} file - SdlFile with file name and one of A) fileData, B) Uri, or C) resourceID set
```
Fixes issues found by linter.

File: lib/js/src/manager/file/filetypes/SdlFile.js [hunk 2]
```diff
@@ -158,6 +159,24 @@ class SdlFile {
     isStaticIcon () {
         return this._isStaticIcon;
     }
+
+    /**
+     * Sets the overwrite property for an SdlFile
+     * @param {Boolean} fileName - A boolean value that indicates if the file can be overwritten
```
Comment (renonick87) [inline lib/js/src/manager/file/filetypes/SdlFile.js:165]:
```suggestion
     * @param {Boolean} overwrite - A boolean value that indicates if the file can be overwritten
```
Fixes issues found by linter.

File: lib/js/src/manager/screen/_SoftButtonManagerBase.js [hunk 3]
```diff
@@ -199,7 +199,9 @@ class _SoftButtonManagerBase extends _SubManagerBase {
                 }
                 if (initialState !== null && Array.isArray(softButtonObject.getStates())) {
                     for (const softButtonState of softButtonObject.getStates()) {
-                        if (softButtonState !== null && softButtonState.getName() !== null && this._sdlArtworkNeedsUpload(softButtonState.getArtwork())) {
+                        if (softButtonState !== null && softButtonState.getName() !== null && 
+                            this._fileManager !== null && this._fileManager !== undefined &&
```
Comment (renonick87) [inline lib/js/src/manager/screen/_SoftButtonManagerBase.js:203]:
```suggestion
                        if (softButtonState !== null && softButtonState.getName() !== null &&
                            this._fileManager !== null && this._fileManager !== undefined &&
```
Fix issues found by linter. No trailing spaces allowed.

**Review by renonick87 — APPROVED** [review]
