### PR TITLE
Bugfix/webengine app icon

### LINKED ISSUE #238: Webengine apps don't upload the app icon image properly
### Bug Report
The `LifecycleConfig.loadManifest()` doesn't read the manifest's `appIcon` property, which consequently means the app icon won't be set in the lifecycle config and the image won't appear on start up.

##### Expected Behavior
The webengine app's icon should display on connection to the HMI

##### Observed Behavior
There's no image on the HMI on connection

### PR DESCRIPTION
**Pull request by crokita**
Fixes #238 

This PR is ready for review.

### Risk
This PR makes no API changes.

### Summary
Fixes the lifecycle config not reading the app icon from the manifest file for webengine apps.

Merge #242  first

### CODE REVIEW

File: lib/js/src/manager/LifecycleConfig.js [hunk 1]
```diff
@@ -365,6 +367,34 @@ class LifecycleConfig {
                     this.setMinimumRpcVersion(version);
                     break;
                 }
+                case 'appIcon': {
+                    // split the file path by slashes
+                    const fileNameSplit = manifest[key].split(/[\/\\]/g);
```
Comment (renonick87) [inline lib/js/src/manager/LifecycleConfig.js:372]:
```suggestion
                    const fileNameSplit = manifest[key].split(/[/\\]/g);
```
Removed a `\`. Message from the linter: `Unnecessary escape character: \/`.
