### PR TITLE
Fix T&G issues with updating state rapidly

### LINKED ISSUE #554: Setting bad data in one T&G field then good data quickly in another can lead to the good data failing.
### Bug Summary

See the original issue that this issue is based on [here](https://github.com/smartdevicelink/sdl_ios/issues/1781). 

Failed updates to text and graphics in one field can cause a subsequent update in a different field to also fail, preventing a legitimate update from being displayed on the screen.

### Reproduction Steps

1. Set text field 1 to some string
2. Attempt to set text field 2 to an illegitimate string (ex. a string over 500 characters)
3. Attempt to set text field 2 to a legitimate string immediately after

Expected Behavior:
The illegitimate string fails and the legitimate string succeeds and is displayed.

Observed Behavior:
Both text field 2 strings fail and do not display.

### Which projects have you seen this bug on?

_No response_

### JavaScript Version(s)

1.7.0

### sdl_javascript Version

1.7.0

### Testing Environment(s)

```markdown
Manticore v2.10.0
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by crokita**
Fixes #554 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

#### Unit Tests
Add tests for the new _updateTargetStateWithErrorState method

### Summary
When sending updates of invalid data followed by valid data to the T&G manager, the valid data will not be thrown out with the invalid data.

##### Bug Fixes
Resolved an issue with _updatePendingOperationsWithNewScreenData where the wrong identifier was used in the for loop for looping over tasks.

Also fixed _TextAndGraphicUpdateOperation to properly await on sending shows so that the task does not immediately complete.

Fixed variables in test returning undefined due to non-existent SDL.rpc.enums.MetadataType.MEDIA_TITLE value.

### CODE REVIEW

**Comment by theresalech** [comment]
@renonick87 while reviewing, please verify that this check is in place: https://github.com/smartdevicelink/sdl_ios/pull/2107/commits/8180e65affca9258425cef1f016b36768c18c288

**Review by renonick87 — CHANGES_REQUESTED** [review]

File: lib/js/src/manager/screen/_TextAndGraphicManagerBase.js [hunk 1]
```diff
@@ -139,17 +138,6 @@ class _TextAndGraphicManagerBase extends _SubManagerBase {
      * @param {function} listener - A function to invoke when the update task is complete once it runs
      */
     _sdlUpdate (supersedePreviousOperations, listener) {
```
Comment (JulianKast) [inline lib/js/src/manager/screen/_TextAndGraphicManagerBase.js:140]: supersedePreviousOperations is not used anymore

File: lib/js/src/manager/screen/_TextAndGraphicManagerBase.js [hunk 2]
```diff
@@ -139,17 +138,6 @@ class _TextAndGraphicManagerBase extends _SubManagerBase {
...
-            if (typeof this._currentOperationListener === 'function') {
-                this._currentOperationListener(false);
-            }
-        }
-
-        if (this._updateOperation !== null && this._updateOperation.getState() === _Task.IN_PROGRESS && supersedePreviousOperations) {
-            this._updateOperation.switchStates(_Task.CANCELED);
-        }
-
         this._currentOperationListener = listener;
```
Comment (JulianKast) [inline lib/js/src/manager/screen/_TextAndGraphicManagerBase.js:141]: You should be able to get rid of `_currentOperationListener`

**Review by renonick87 — APPROVED** [review]
