### PR TITLE
Make detaching listener happen all the time in finishOperation

### LINKED ISSUE #497: _PresentChoiceSetOperation doesn't remove keyboard listener in all cases
### Bug Report
The keyboard input listener has more cases where it gets attached to the rpc listeners than cases where it gets removed. This creates scenarios where listeners continue to be active after _PresentChoiceSetOperation (_PreloadPresentChoicesOperation in the next release) is finished. No request to activate the keyboard is needed. Multiple errors get logged on every keypress.

##### Reproduction Steps
1. Send multiple valid choice sets 
2. Invoke screen manager's presentKeyboard
3. Use the on-screen keyboard

##### Expected Behavior
Each button press should invoke a listener one time for every event

##### Observed Behavior
Each button press invokes multiple listeners for each event, depending on how many times choice sets were uploaded.

##### Browser & Version Information
1.4 on all environments.

##### Test Case, Sample Code, and / or Example App
Run the screen-choices test for the test suite in feature/release-tests

### PR DESCRIPTION
**Pull request by crokita**
Fixes #497 

### Risk
This PR makes no API changes.

### Testing Plan
- [x] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [x] I have verified that this PR passes lint validation
- [x] I have run the unit tests with this PR
- [x] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

### Summary
Moves the teardown of the keyboard listener to the beginning of the finishOperation to prevent hanging listeners from continuing to function after the operation ends.

### CODE REVIEW

File: lib/js/src/manager/screen/choiceset/_PreloadPresentChoicesOperation.js [hunk 1]
```diff
@@ -703,6 +703,9 @@ class _PreloadPresentChoicesOperation extends _Task {
             this._completionListener(this._loadedCells, success);
         }
 
+        // detach the OnKeyboardInput listener at the end
+        this._lifecycleManager.removeRpcListener(FunctionID.OnKeyboardInput, this._keyboardRpcListener);
```
Comment (renonick87) [inline lib/js/src/manager/screen/choiceset/_PreloadPresentChoicesOperation.js:707]: Removing the listener should be done after checking that the lifecycleManager is not null.

**Review by renonick87 — CHANGES_REQUESTED** [review]

**Review by renonick87 — APPROVED** [review]
