### PR TITLE
Feature/struct message fixes

### LINKED ISSUE #61: RPC Struct and Messages Have Bad Keys
### Bug Report
Some of the keys used in the rpc messages and structs are wrong. They either point to the wrong thing or something that does not exist.

##### Reproduction Steps
Create an RPC message or struct for one of the affected classes. Try to set and get affected variables. Observe that the variables are not set and fetched properly.

##### Expected Behavior
Should be able to use setters and getters.

##### Observed Behavior
Unable to set and get for some structs and messages.

### PR DESCRIPTION
**Pull request by russjohnson09**
Fixes #61 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
These are issues found while writing unit tests for issue #60. They will be tested when this issue is resolved, but creating a message and struct and using the set and get methods should work now for the updated classes.

### Summary
Fixes bad references to the set and get parameter methods.

### Tasks Remaining:
None

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

File: lib/js/src/rpc/structs/Image.js [hunk 1]
```diff
@@ -43,10 +43,10 @@ class Image extends RpcStruct {
     }
 
     /**
-    * @param {String} value
+    * @param {String} Value
```
Comment (crokita) [inline lib/js/src/rpc/structs/Image.js]: It should be value with a lowercase V

Comment (russjohnson09) [reply lib/js/src/rpc/structs/Image.js]:
```suggestion
    * @param {String} value
```
