### PR TITLE
Bugfix/send sequential rpcs align

### LINKED ISSUE #235: Misaligned SdlManager sendSequentialRpcs method
##### Expected Behavior
In other projects for `sendSequentialRpcs`, a listener is invoked for every completion of an RPC sent, which means every RPC response should be returned through the listener.

##### Observed Behavior
The promise just resolves to the last RPC response, since `reduce` is used under the hood. It should return an array of RPC responses instead, with each RPC being executed in order and pausing execution for every response.

### PR DESCRIPTION
**Pull request by crokita**
Fixes #235 

This PR is ready for review.

### Risk
This PR makes minor API changes.

### Summary
Introduces a replacement method for `sendSequentialRpcs` that will return the array of responses even when some of them fail. Also adds an update handler callback that informs the user of completed RPCs and how many are remaining.

Merge #241 before this one

### CODE REVIEW

File: lib/js/src/manager/SdlManager.js [hunk 1]
```diff
@@ -432,6 +457,31 @@ class SdlManager extends _SdlManagerBase {
...
+     * Sends multiple RPCs synchronously (in order)
+     * @param {RpcMessage[]} messages - An array of RpcMessages
+     * @param {function} onUpdate - A callback function that will be invoked with the result and the remaining requests left
+     * @returns {Promise} - A Promise which returns all responses when they all resolve, regardless of the result code
+     */
+    async sendSequentialRpcsResolve (messages, onUpdate) {
+        if (!Array.isArray(messages)) {
+            return Promise.reject('messages is not an array');
+        }
+        let resolvedRpcs = [];
```
Comment (renonick87) [inline lib/js/src/manager/SdlManager.js:470]: From the linter:
```
'resolvedRpcs' is never reassigned. Use 'const' instead.
```
