### PR TITLE
WebSocket Server Support for Multiple Client Connections

### LINKED ISSUE #99: Manage Multiple Connections as Isolated Sessions
### Bug Report
Currently, when multiple Core instances connect to an SDL JavaScript WebSocket Server, SDL payloads (responses, notifications) are sent to *all* connected Core clients instead of the individual Core client responsible for the original request/subscription.

##### Expected Behavior
Each connection from Core should be treated as an isolated session to avoid cross-contamination of RPC responses/notifications, which would lead to unexpected behavior.

##### Test Case, Sample Code, and / or Example App
The `hello-sdl` Node app exemplifies the problem.

### PR DESCRIPTION
**Pull request by nickschwab**
Fixes #99 

This PR is **ready** for review.

### Risk
This PR makes **minor** API changes.

### Testing Plan
Run the Node.js example app and connect 2 or more Core clients to it simultaneously.

### Summary
Changed the WebSocketServer transport to act in scope of a single client connected to the server to allow for multiple, isolated client connections. This change is heavily based off of the Java Suite's implementation and intended use of the WebSocketServer transport.

A working example of this can be found in the Node.js example project.

### CLA
- [x] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform) and this pull request adheres to the [Contributing Guide](./CONTRIBUTING.md).

### CODE REVIEW

File: lib/node/src/transport/WebSocketServer.js [hunk 1]
```diff
@@ -31,109 +31,80 @@
...
-                    client.isAlive = false;
-                    console.log('server sending ping to client');
-                    client.ping(function () {});
-                });
-            }, this._transportConfig.getConnectionLostTimeout());
+        if (connectionLostTimeout > 0) {
+            this._connectionLostInterval = setInterval(() => {
+                if (client.isAlive === false) {
+                    console.log('server deemed client dead');
+                    return client.terminate();
```
Comment (russjohnson09) [inline lib/node/src/transport/WebSocketServer.js]: I think this works for terminating the client but the setInterval will continuing running. I think making a call to clearInterval is also needed here. I am receiving a lot of "server deemed client dead". I shouldn't be receiving this after the client connection has been terminated.

Comment (nickschwab) [reply lib/node/src/transport/WebSocketServer.js]: @russjohnson09 Thanks! I moved the logic to terminate the interval from the stop() method to the connection closed event listener.
