### PR TITLE
Fix case where file can have multiple upload/delete tasks created for it

### LINKED ISSUE #483: File Manager will upload the same file multiple times
### Bug Report
When trying to load multiple of the same artwork and the file is not uploaded yet, the file will be uploaded multiple times. This is because we create multiple of the same upload operation and they all execute.

We should probably implement the upload / delete operation to check if the file needs to be uploaded at the time it would run instead of the manager figuring out if the operation should be created at all.

##### Reproduction Steps
1. Create 99 SDLArtworks that are exactly the same
2. Attempt to upload all 99 with the uploadFiles method.

##### Expected Behavior
The one artwork should only be uploaded 1 time.

##### Observed Behavior
The one artwork will be uploaded 99 times, slowing down the head unit like crazy.

##### Test Case, Sample Code, and / or Example App
```
const newFile = new SDL.manager.file.filetypes.SdlArtwork('sdl-logo-new', SDL.rpc.enums.FileType.GRAPHIC_PNG)
    .setFilePath(this._filePath);
const dupeFiles = [newFile, newFile, newFile, newFile, newFile, newFile, newFile, newFile, newFile];
await this._sdlManager.getFileManager().uploadFiles(dupeFiles);
```
The above file will be uploaded 9 separate times.

### PR DESCRIPTION
**Pull request by renonick87**
Fixes #483 

### Risk
This PR makes **minor** API changes.

### Testing Plan
- [X] I have verified that I have not introduced new warnings in this PR (or explain why below)
- [X] I have verified that this PR passes lint validation
- [X] I have run the unit tests with this PR
- [X] I have tested this PR against Core and verified behavior (if applicable, if not applicable, explain why below).

### Summary
This PR fixes the case where multiple upload/delete operations could be queued for the same file, resulting in the file being uploaded/deleted several times.

### CLA
- [X] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)

### CODE REVIEW

**Review by crokita — CHANGES_REQUESTED** [review]
See feedback

File: lib/js/src/manager/file/filetypes/SdlFile.js [hunk 1]
```diff
@@ -223,6 +223,9 @@ class SdlFile {
     clone () {
         const clonedParams = Object.assign({}, this); // shallow copy
 
+        if (this.getFileData() !== null && this.getFileData() !== undefined) {
+            return Object.assign(new SdlFile(this.getName(), this.getType(), Uint8Array.from(this.getFileData()), this.isPersistent()), clonedParams);
```
Comment (crokita) [inline lib/js/src/manager/file/filetypes/SdlFile.js:227]: The parameters for Object.assign go as follows: target, source. This means that the second parameter's properties will overwrite whatever is in the first object's properties. In this case, the newly constructed fileData in the first argument is overwritten by the clonedParams, and the deep cloning isn't fully achieved. You may want to check the SdlArtwork clone method for the same reason.

**Review by crokita — CHANGES_REQUESTED** [review]
See feedback

**Review by crokita — APPROVED** [review]
